USE MED_PAC

ALTER TABLE CONSULTA
  ADD VrConsulta MONEY CHECK( VrConsulta > 0);

ALTER TABLE MEDICOS
 ALTER COLUMN NmMedico VARCHAR(100) not null UNIQUE;

ALTER TABLE MEDICOS ALTER COLUMN NmMedico VARCHAR(100) UNIQUE(NmMedico) not null;