CREATE DATABASE MED_PAC

USE MED_PAC

CREATE TABLE AMBULATORIOS
	(NrAmbul		VARCHAR(03) PRIMARY KEY,
		 NrAndar	NUMERIC(04) NOT NULL ,
		 Capacidade NUMERIC(06) NOT NULL CHECK(Capacidade > 0));

CREATE TABLE MEDICOS
	(CRM				VARCHAR(06)		PRIMARY KEY,
		RGMedico		VARCHAR(12)		NOT NULL ,
		NmMedico		VARCHAR(50)		NOT NULL UNIQUE,
		Idade			NUMERIC(06)		NOT NULL,
		Cidade			VARCHAR(50)		NOT NULL,
		Especialidade	VARCHAR(50)		NOT NULL,
		NrAmbul			VARCHAR(03)		REFERENCES AMBULATORIOS);

CREATE TABLE PACIENTES
	(RGPaciente		VARCHAR(12)		PRIMARY KEY,
		NmPaciente	VARCHAR(100)	NOT NULL UNIQUE,
		Sexo		CHAR(01)		check (Sexo IN ('F', 'M')) NOT NULL,
		Idade		NUMERIC(06)		NOT NULL,
		Cidade		VARCHAR(50)		check (Cidade IN ('Itu','Salto','Sorocaba')),
		Doenca		VARCHAR(100)	NOT NULL);

CREATE TABLE CONSULTA
	(CRM			VARCHAR(06)	REFERENCES MEDICOS,
		RGPaciente	VARCHAR(12) REFERENCES PACIENTES,
		Data_hora	DATETIME	NOT NULL,
		PRIMARY KEY (CRM,RGPaciente));






