#include <iostream>
#include <stdlib.h>

main() {
	//FAÇA UM PROGRAMA QUE LEIA O TAMANHO DE UM VETOR DE INTEIROS 
	//E RESERVE DINAMICAMENTE MEMÓRIA PARA ESSE VETOR. EM SEGUIDA, 
	//IMPRIMA O VETOR LIDO E MOSTRE O RESULTADO DA SOMA DOS NÚMEROS 
	//ÍMPARES PRESENTES NO VETOR (OBS: NÃO USE ALOCAÇÃO ESTÁTICA).
	
	
}
