CREATE PROCEDURE NovaRegiao 
	@nome VARCHAR(20)
AS
	BEGIN TRANSACTION
	INSERT INTO regiao VALUES(@nome)

	IF @@ERROR <> 0
		BEGIN
			PRINT('ERRO NA INSERÇÃO!')
			ROLLBACK TRANSACTION
			RETURN
		END
	ELSE
		BEGIN
			PRINT('REGISTRO INSERIDO!')
			COMMIT TRANSACTION
			RETURN
		END
