CREATE TABLE AMBULATORIOS(
	NrAmbul VARCHAR(3) PRIMARY KEY,
	NrAndar Numeric(4, 0) NOT NULL,
	Capacidade NUMERIC(6, 0) NOT NULL CHECK(Capacidade > 0)
)
GO

CREATE TABLE MEDICOS(
	CRM Varchar(6) PRIMARY KEY,
	RGMedico VARCHAR(12) NOT NULL,
	NmMedico VARCHAR(50) NOT NULL UNIQUE,
	Idade NUMERIC(6,0) NOT NULL,
	Cidade VARCHAR(50),
	Especialidade VARCHAR(50) NOT NULL,
	Nr_Ambul VARCHAR(3)
)
GO

CREATE TABLE PACIENTES(
	RGPaciente VARCHAR(12) PRIMARY KEY,
	NmPaciente VARCHAR(100) NOT NULL UNIQUE,
	Sexo CHAR(1) NOT NULL CHECK(Sexo IN('M','F')),
	Idade NUMERIC(6,0) NOT NULL,
	Cidade VARCHAR(50) CHECK(Cidade IN('Itu','Salto','Sorocaba')),
	Doenca VARCHAR(100) NOT NULL
)
GO

CREATE TABLE CONSULTA(
	CRM_RGPaciente VARCHAR(10) PRIMARY KEY,
	CRM VARCHAR(6),
	RGPaciente VARCHAR(12),
	Data_hora DATETIME NOT NULL,
)
GO

ALTER TABLE MEDICOS
ADD CONSTRAINT FK_MEDICO_AMBULATORIO
FOREIGN KEY(Nr_Ambul)
REFERENCES AMBULATORIOS(NrAmbul)
GO

ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CONSULTA_MEDICOS
FOREIGN KEY(CRM)
REFERENCES MEDICOS(CRM)
GO

ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CONSULTA_RGPaciente
FOREIGN KEY(RGPaciente)
REFERENCES PACIENTES(RGPaciente)
GO